config/routes.rb
Library::Application.routes.draw do

  resources :user_configs
  resources :tags
  resources :books do
    resources :reviews
    resources :preferences
  end

  get '/books/:id/follow(.:format)', to: 'books#follow', as: :follow_book
  get '/books/:id/stop_following(.:format)', to: 'books#stop_following', as: :stop_following_book

  get "home/index"
  get '/home/reports(.:format)', to: 'home#reports', as: :user_reports
  get '/home/invite_user(.:format)', to: 'home#invite_user', as: :invite_user

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  devise_scope :user do
    get 'sign_in', to: 'home#index', as: :new_user_session
    get 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  get '/users', to: 'users#index', as: :users
  match '/users/:id', to: 'users#update', as: :user, via: [:get, :patch]
  get '/users/:id/edit(.:format)', to: 'users#edit', as: :edit_user

  root 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: :invite_user
  def index
  	if !user_signed_in?
  		flash[:notice] = "Please sign in with your Google account to access all features of this website!"
  	end
  end

  def invite_user
    LibraryMailer.invite_user(params[:email], User.find(current_user.id)).deliver
  	render 'index'
  end

private
    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params.require(:home).permit(:email)
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_invite_user_form.html.erb
<%= form_tag(invite_user_path, method: "get", options: { class: "navbar-form navbar-left"}) do %>
	<div class="row-fluid">
		<div class="panel panel-primary">
		  	<div class="panel-body">
			  	<div class="form-group">
			  		<h4>Invite Friends!</h4>
			  		<div class="form-control">
			    		<%= email_field_tag(:email, "", class: "text_field") %>
		  			</div>
			  		<div class="form-control">
			    		<%= submit_tag "Invite", class: "btn btn-primary" %>
		  			</div>
		  		</div>
		    </div>
		</div>
	</div>
<% end %>

app/views/home/index.html.erb
<% if user_signed_in? %>
	<div class="well">
		<%= render :partial => 'invite_user_form' %>
	</div>
<% end %>