config/routes.rb
Library::Application.routes.draw do

  resources :user_configs
  resources :tags
  resources :books do
    resources :reviews
    resources :preferences
  end

  get '/books/:id/follow(.:format)', to: 'books#follow', as: :follow_book
  get '/books/:id/stop_following(.:format)', to: 'books#stop_following', as: :stop_following_book

  get "home/index"
  get '/home/reports(.:format)', to: 'home#reports', as: :user_reports
  get '/home/invite_user(.:format)', to: 'home#invite_user', as: :invite_user

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  devise_scope :user do
    get 'sign_in', to: 'home#index', as: :new_user_session
    get 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  get '/users', to: 'users#index', as: :users
  match '/users/:id', to: 'users#update', as: :user, via: [:get, :patch]
  get '/users/:id/edit(.:format)', to: 'users#edit', as: :edit_user

  root 'home#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
	belongs_to :user
	has_many :reviews
	
	has_many :follows
    has_many :followers, through: :follows, source: :user

	has_many :opted_outs
    has_many :opted_out_users, through: :opted_outs, source: :user

    has_many :book_tags
    has_many :tags, through: :book_tags

	mount_uploader :image, S3Uploader
    validates :title, :author, :isbn, presence: true
    validates :isbn, uniqueness: true

	def avg_rating
		if !self.reviews.empty?
			self.reviews.collect{ |r| r.rating }.reduce(:+) / self.reviews.size
		else
			" - "
		end
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :follow, :stop_following]
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy, :follow, :stop_following]
  load_and_authorize_resource :only => [:edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    if view_context.is_admin?
      @books = Book.all
    elsif user_signed_in?
      @books = Book.where("is_approved = ? or user_id = ?", true, current_user.id)
    else
      @books = Book.where("is_approved = ?", true)
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    if user_signed_in?
      @book_preferences = OptedOut.where("book_id = ? AND user_id = ?",params[:id], current_user.id)[0]
      @is_followed_by_cuurent_user = Follow.find_by_book_id_and_user_id(@book.id, current_user.id).nil?
    end
  end

  # GET /books/new
  def new
      @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
      @book = Book.new(book_params)
      @book.user_id = current_user.id
      @book.save
      respond_with(@book, :flash => true)
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
      @book.update(book_params)
      respond_with(@book, :flash => true)
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
      @book.destroy
      respond_with(@book, :flash => true)
  end

  def follow
      @follow = Follow.new
      @follow.user_id = current_user.id
      @follow.book_id = @book.id
      if !@follow.save
        flash[:error] = "Unable to process your request. Please try after some time."
      else
        flash[:notice] = "You have elected to follow this book.
                              You would receive review/rating mails, if enabled in preferences."
        LibraryMailer.on_follow(@follow).deliver
      end
      redirect_to book_path
  end

  def stop_following
      count = Follow.delete_all(["book_id = ? AND user_id = ?", @book.id, current_user.id])
      if !count
        flash[:error] = "Unable to process your request. Please try after some time."
      else
        flash[:notice] = "You had stopped following this book successfully."
      end
      redirect_to book_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author, :isbn, :image, :is_active, :is_approved, tag_ids: [])
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for @book, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :author, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :author, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :isbn, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :isbn, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :image, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :image, :class => 'file_field' %>
      <% if @book.image? %>
        <%= image_tag(@book.image_url(:thumb), class: "img-thumbnail") %>
      <% else %>
        <%= image_required_message %>
      <% end %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :tags, :class => 'control-label' %>
    <div class="controls">
      <%= f.collection_select(:tag_ids, Tag.all, :id, :name, {selected: @book.tag_ids},{ multiple: true }) %>
    </div>
  </div>
  <% if @book.is_approved? %>
    <div class="control-group">
      <%= f.label :is_active, :class => 'control-label' %>
      <div class="controls">
        <%= f.check_box :is_active, :class => 'check_box' %>
      </div>
    </div>
  <% end %>
  <% if is_admin? && can_be_approved?(@book) %>
    <div class="control-group">
      <%= f.label :approve, :class => 'control-label' %>
      <div class="controls">
        <%= f.check_box :is_approved, :class => 'check_box' %>
      </div>
    </div>
  <% end %>

  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
              books_path, :class => 'btn' %>

<% end %>

app/views/books/_reviews.html.erb
<%- model_class = Review -%>
<script>
  $(document).ready(function() {
      $('#book-reviews').dataTable({
        "order": [[ 0, "desc" ]]
    });
  } );
</script>
<table id="book-reviews" class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:rating) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @book.reviews.each do |review| %>
      <tr>
        <td><%= review.rating %></td>
        <td><%= short_string_for(review.description, 30) %></td>
        <td>
          <%= link_to 'Details', book_review_path(@book, review),  :class => 'btn btn-mini' %>
          <% if can? :eud, review %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_book_review_path(@book, review), :class => 'btn btn-mini' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        book_review_path(@book, review),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-mini btn-danger' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h3><%=t '.title', :default => @book.title.titleize %></h3>
</div>
<%= render :partial => 'form' %>

app/views/books/index.html.erb
<%- model_class = Book -%>
<%= nav_bar :fluid => :top, :brand => model_class.model_name.human.pluralize.titleize, :responsive => true do %>
  <%= menu_group :pull => :right do %>
    <% if ( user_signed_in?) %>
      <%= drop_down_with_submenu "Actions" do %>
        <%= menu_item t('.new', :default => t("helpers.links.new")), new_book_path %>
      <% end %>
    <% end %>
  <% end %>
<% end %>
<script>
  $(document).ready(function() {
      $('#books').dataTable({
        "order": [[ 4, "desc" ]]
    });
  } );
</script>
<table id="books" class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(" ") %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:author) %></th>
      <th><%= model_class.human_attribute_name(:isbn) %></th>
      <th><%= titleize_column_name(model_class.human_attribute_name(:avg_rating)) %></th>
      <th><%= model_class.human_attribute_name(:tags) %></th>
      <% if ( user_signed_in? ) %>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to(image_tag(book.image_url(:thumb), class: "img img-thumbnail"), book_path(book)) %></td>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.isbn %></td>
        <td><%= book.avg_rating %></td>
        <td><%= short_string_for(tag_helper(book), 20) %></td>
        <td>
          <% if (can_be_reviewed?(book)) %>
            <%= link_to 'Review', new_book_review_path(book.id), :class => 'btn btn-mini' %>
          <% end %>
          <% if ( is_admin? || is_owner?(book)) %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_book_path(book), :class => 'btn btn-mini' %>
            <% if ( book.reviews.empty? ) %>
              <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                          book_path(book),
                          :method => :delete,
                          :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                          :class => 'btn btn-mini btn-danger' %>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/new.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h3><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h3>
</div>
<%= render :partial => 'form' %>

app/views/books/show.html.erb
<%- model_class = Book -%>
<%= nav_bar :fluid => :top, :brand => @book.title.titleize, :responsive => true do %>
  <%= menu_group :pull => :right do %>
    <% if ( user_signed_in? ) %>
      <%= drop_down_with_submenu "Actions" do %>
        <% if (can? :eud, @book) %>
          <%= menu_item t('.edit', :default => t("helpers.links.edit")), edit_book_path(@book) %>
          <% if ( @book.reviews.empty? ) %>
            <%= menu_item t('.destroy', :default => t("helpers.links.destroy")), book_path(@book),
                      :method => 'delete',
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) } %>
          <% end %>
          <%= drop_down_divider %>
        <% end %>
        <% if ( can_be_reviewed?(@book) ) %>
          <%= menu_item 'Add Review', new_book_review_path(@book.id) %>
          <%= drop_down_divider %>
          <% if ( @is_followed_by_cuurent_user ) %>
            <%= menu_item 'Follow', follow_book_path(@book) %>
          <% else %>
            <%= menu_item 'Stop Following', stop_following_book_path(@book) %>
          <% end %>
          <% if ( @book_preferences.nil? ) %>
            <%= menu_item 'Preferences', new_book_preference_path(@book.id) %>
          <% else %>
            <%= menu_item 'Preferences', book_preference_path(@book.id, @book_preferences) %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
<% end %>
<div class="row-fluid">
  <div class="span4">
    <dl class="dl-horizontal">
      <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
      <dd><%= @book.title %></dd>
      <dt><strong><%= model_class.human_attribute_name(:author) %>:</strong></dt>
      <dd><%= @book.author %></dd>
      <dt><strong><%= model_class.human_attribute_name(:isbn) %>:</strong></dt>
      <dd><%= @book.isbn %></dd>
      <dt><strong><%= model_class.human_attribute_name(:avg_rating) %>:</strong></dt>
      <dd><%= @book.avg_rating %></dd>
      <dt><strong><%= model_class.human_attribute_name(:tags) %>:</strong></dt>
      <dd><%= tag_helper(@book) %></dd>
    </dl>
  </div>
  <div class="span6">
    <dl class="dl-horizontal">
      <dd><%= image_tag(@book.image_url, class: "img") %></dd>
    </dl>
  </div>
</div>

<%= link_to t('.back', :default => t("helpers.links.back")),
            books_path, :class => 'btn btn-mini'  %>
<div class="row-fluid">

  <div class="page-header">
  </div>
  <% if ( !@book.reviews.empty? ) %>
    <div class="row-fluid">
      <%= render "reviews" %>
    </div>
  <% end %>
</div>