config/routes.rb
Library::Application.routes.draw do

  resources :user_configs
  resources :tags
  resources :books do
    resources :reviews
    resources :preferences
  end

  get '/books/:id/follow(.:format)', to: 'books#follow', as: :follow_book
  get '/books/:id/stop_following(.:format)', to: 'books#stop_following', as: :stop_following_book

  get "home/index"
  get '/home/reports(.:format)', to: 'home#reports', as: :user_reports
  get '/home/invite_user(.:format)', to: 'home#invite_user', as: :invite_user

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  devise_scope :user do
    get 'sign_in', to: 'home#index', as: :new_user_session
    get 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  get '/users', to: 'users#index', as: :users
  match '/users/:id', to: 'users#update', as: :user, via: [:get, :patch]
  get '/users/:id/edit(.:format)', to: 'users#edit', as: :edit_user

  root 'home#index'

end

app/models/tag.rb
class Tag < ActiveRecord::Base
    has_many :book_tags
    has_many :books, through: :book_tags

	validates :name, :description, presence: true
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  load_and_authorize_resource param_method: :tag_params

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
      @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
      @tag = Tag.new(tag_params)
      @tag.save!
      respond_with(@tag, :flash => true)
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
      @tag.update(tag_params)
      respond_with(@tag, :flash => true)
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
      @tag.destroy
      respond_to do |format|
        format.html { redirect_to tags_url }
        format.json { head :no_content }
      end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name, :description)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_for @tag, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field' %>
    </div>
  </div>

  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
              tags_path, :class => 'btn' %>

<% end %>

app/views/tags/edit.html.erb
<%- model_class = Tag -%>
<div class="page-header">
  <h4><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h4>
</div>
<%= render :partial => 'form' %>

app/views/tags/index.html.erb
<%- model_class = Tag -%>
<%= nav_bar :fluid => :top, :brand => model_class.model_name.human.pluralize.titleize, :responsive => true do %>
  <%= menu_group :pull => :right do %>
    <% if ( current_user.try(:is_admin?) ) %>
      <%= drop_down_with_submenu "Actions" do %>
        <%= menu_item t('.new', :default => t("helpers.links.new")), new_tag_path %>
      <% end %>
    <% end %>
  <% end %>
<% end %>
<script>
  $(document).ready(function() {
      $('#tags').dataTable();
  } );
</script>
<table id="tags" class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <% if current_user.try(:is_admin?) %>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      <% end %> 
    </tr>
  </thead>
  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td><%= tag.description %></td>
        <% if current_user.try(:is_admin?) %>
          <td>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_tag_path(tag), :class => 'btn btn-mini' %>
            <% if (!is_tag_used?(tag)) %>
              <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                          tag_path(tag),
                          :method => :delete,
                          :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                          :class => 'btn btn-mini btn-danger' %>
            <% end %>
          </td>
        <% end %> 
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tags/new.html.erb
<%- model_class = Tag -%>
<div class="page-header">
  <h4><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h4>
</div>
<%= render :partial => 'form' %>

app/views/tags/show.html.erb
<%- model_class = Tag -%>
<div class="page-header">
  <h4><%=t '.title', :default => @tag.name.titleize %></h4>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @tag.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @tag.description %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
            tags_path, :class => 'btn'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
            edit_tag_path(@tag), :class => 'btn' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
            tag_path(@tag),
            :method => 'delete',
            :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
            :class => 'btn btn-danger' %>