config/routes.rb
Library::Application.routes.draw do

  resources :user_configs
  resources :tags
  resources :books do
    resources :reviews
    resources :preferences
  end

  get '/books/:id/follow(.:format)', to: 'books#follow', as: :follow_book
  get '/books/:id/stop_following(.:format)', to: 'books#stop_following', as: :stop_following_book

  get "home/index"
  get '/home/reports(.:format)', to: 'home#reports', as: :user_reports
  get '/home/invite_user(.:format)', to: 'home#invite_user', as: :invite_user

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  devise_scope :user do
    get 'sign_in', to: 'home#index', as: :new_user_session
    get 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  get '/users', to: 'users#index', as: :users
  match '/users/:id', to: 'users#update', as: :user, via: [:get, :patch]
  get '/users/:id/edit(.:format)', to: 'users#edit', as: :edit_user

  root 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Library" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <div class="container-fluid">
      <div class="container-fluid">
        <div class="row-fluid">
          <%= nav_bar :fluid => :top, :brand => "the Library", :responsive => true do %>
            <%= menu_group :pull => :right do %>
              <% if user_signed_in? %>
                <%= drop_down_with_submenu current_user.email do %>
                  <% if current_user.try(:is_admin?) %>
                    <%= drop_down_submenu "Admin" do %>
                      <%= menu_item "Reports", user_reports_path %>
                      <%= menu_item "Users", users_path %>
                    <% end %>
                    <%= drop_down_divider %>
                  <% end %>
                  <%= menu_item "Preferences", user_config_path(current_user.id) %>
                  <%= drop_down_divider %>
                  <%= menu_item "Sign out", destroy_user_session_path %>
                <% end %>
              <% else %>
                <%= menu_item "Sign in with Google", user_omniauth_authorize_path(:provider => "google_oauth2") %>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="container-fluid">
        <div class="row-fluid">
          <div class="span2">
            <div class="well sidebar-nav">
              <ul class="nav nav-list">
                <li><%= link_to "Home", home_index_path  %></li>
                <li><%= link_to "Books", books_path  %></li>
                <li><%= link_to "Valid Tags", tags_path  %></li>
              </ul>
            </div>
          </div>
          <div class="span10">
            <div id="main-data" class="container-fluid">
              <%= render partial: "shared/flash_messages", flash: flash %> 
              <%= yield %>
            </div>
          </div>
        </div>
      </div>
      <!--<div class="container-fluid">
        <div class="row-fluid">
          <footer>
            <%= nav_bar :fluid => :bottom, :responsive => true do %>
              <%= menu_group do %>
                <%= menu_item "Home", home_index_path %>
                <%= menu_divider %>
                <% if current_user %>
                  <%= menu_item "Sign out", destroy_user_session_path %>
                <% end %>
              <% end %>
                <%= menu_text "(c) ViswaJyothi Schools 2014", :pull => :right %>
            <% end %>
          </footer>
        </div>
      </div> -->
    </div>
  </body>
</html>